[extend]
useDefault = true

[allowlist]
description = "Ignore disabled mock secret files and examples"
paths = [
    '''\.env$''',
    '''\.env\.app-secrets$''',
    '''\.env\.app-secrets\.example$''',
    '''kubeconfig$''',
    '''terraform/secrets\.tfvars$''',
    '''secrets\.tfvars\.example$''',
    '''external-secret\.yaml$'''
]
