---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-staging-secrets
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: directus-staging-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET
      remoteRef:
        key: DIRECTUS_STAGING_SECRET
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: DIRECTUS_STAGING_ADMIN_EMAIL
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: DIRECTUS_STAGING_ADMIN_PASSWORD
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DIRECTUS_STAGING_DB_PASSWORD
    # Authentik OIDC SSO
    - secretKey: AUTH_AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: DIRECTUS_STG_OIDC_CLIENT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-staging-db-credentials
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: directus-staging-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: "directus"
        password: "{{ .DIRECTUS_STAGING_DB_PASSWORD }}"
  data:
    - secretKey: DIRECTUS_STAGING_DB_PASSWORD
      remoteRef:
        key: DIRECTUS_STAGING_DB_PASSWORD
