---
apiVersion: v1
kind: Service
metadata:
  name: directus
  namespace: staging
  labels:
    app: directus
    env: staging
spec:
  type: ClusterIP
  selector:
    app: directus
    env: staging
  ports:
    - name: http
      port: 80
      targetPort: 8055
