"""画面表記定義。文言の正本は design.md「画面表記定義」で、キーも同じ。"""

LABELS: dict[str, str] = {
    "status.ok": "正常",
    "status.warn": "警告",
    "status.crit": "異常",
    "status.error": "取得失敗",
    "status.stale": "情報が古い",
    "status.empty": "データなし",
    "meta.fetched_at": "取得時刻: {datetime}",
    "meta.last_success": "最終成功: {datetime}",
    "meta.error_reason": "取得できませんでした ({reason})",
    "meta.source": "取得元: {name}",
    "empty.generic": "該当するデータはありません",
    "empty.collecting": "データを収集中です。次回の取得後に表示されます",
    "unit.count": "件",
    "unit.mail": "通",
    "unit.percent": "%",
    "unit.bytes": "GB / TB (10 進)",
    "unit.currency": "€ / $ (各サービスの請求通貨のまま。換算しない)",
    "table.show_numbers": "数値を表で見る",
    "table.hide_numbers": "表を閉じる",
    "dash.title": "運用ダッシュボード",
    "dash.updated": "最終更新: {datetime}",
    "dash.button.reload": "再読み込み",
    "dash.button.portal": "ポータルへ戻る",
    "dash.button.logout": "ログアウト",
    "dash.summary.title": "要確認の項目",
    "dash.summary.counts": "異常 {crit} 件 / 警告 {warn} 件 / 取得失敗 {error} 件",
    "dash.summary.none": "要確認の項目はありません",
    "dash.range.24h": "24 時間",
    "dash.range.7d": "7 日間",
    "dash.range.30d": "30 日間",
    "dash.range.90d": "90 日間",
    "sec.billing": "課金・利用枠",
    "col.service": "サービス",
    "col.plan": "プラン",
    "col.period": "適用期間",
    "col.billed": "当期の請求額",
    "billed.cloudflare": "契約中のプラン料金 (月額): {amount}",
    "billed.github": "当月の請求見込み: {amount}",
    "billed.na": "請求額を取得する API がありません",
    "sub.hetzner": "Hetzner Cloud",
    "col.server": "サーバー",
    "col.type": "種別",
    "col.location": "場所",
    "col.running_since": "稼働開始",
    "hetzner.estimate": "当月の見込み費用 (税抜): {amount}",
    "hetzner.traffic": "送信量: {used} / 無料枠 {included}",
    "note.server.unexpected": "宣言にないサーバーが稼働しています",
    "note.server.missing": "稼働しているはずのサーバーが見つかりません",
    "col.quota": "利用枠",
    "col.used": "使用量",
    "col.limit": "上限",
    "col.ratio": "使用率",
    "quota.workers_day": "Workers リクエスト数 (本日)",
    "quota.workers_month": "Workers リクエスト数 (当月)",
    "quota.r2_storage": "R2 保存容量",
    "quota.r2_class_a": "R2 Class A 操作数 (当月)",
    "quota.r2_class_b": "R2 Class B 操作数 (当月)",
    "quota.zt_users": "Zero Trust 利用者数",
    "quota.tfc_rum": "HCP Terraform 管理リソース数",
    "quota.infisical_identities": "Infisical identity 数",
    "quota.tailscale_users": "Tailscale ユーザー数",
    "quota.tailscale_devices": "Tailscale デバイス数",
    "quota.netdata_nodes": "Netdata Cloud 接続ノード数",
    "quota.healthchecks": "Healthchecks.io チェック数",
    "quota.uptimerobot": "UptimeRobot モニター数",
    "quota.gh_actions": "GitHub Actions 使用時間 (当月)",
    "quota.gh_packages": "GitHub Packages 保存容量",
    "sub.object_storage": "Hetzner Object Storage",
    "os.total": "使用容量 (合計): {size} / 基本料金に含まれる容量 {included}",
    "os.bucket": "{bucket}: {size}",
    "note.threshold": "警告閾値 ({ratio}%) を超えています",
    "note.over_limit": "上限に達しています",
    "note.plan_revert": "有料プランの適用期間 ({until}) を過ぎています。プランの戻し忘れを確認してください",
    "note.plan_undeclared": "現在の期間に有効なプランが宣言されていません",
    "note.quota_declared_only": "API で取得できないため使用量は表示しません (上限は宣言値)",
    "sub.credentials": "資格情報の期限",
    "col.credential": "資格情報",
    "col.expires_on": "有効期限",
    "note.credential_expiring": "有効期限まで {n} 日です。再発行してください",
    "note.credential_expired": "有効期限が切れています。再発行してください",
    "sec.monitoring": "既存監視",
    "sub.uptimerobot": "UptimeRobot",
    "col.monitor": "モニター",
    "col.state": "現在の状態",
    "state.up": "稼働中",
    "state.down": "停止",
    "state.paused": "一時停止",
    "sub.healthchecks": "Healthchecks.io",
    "col.check": "チェック",
    "col.last_ping": "最終受信",
    "state.hc.up": "正常",
    "state.hc.grace": "猶予中",
    "state.hc.down": "未受信",
    "state.hc.new": "未開始",
    "state.hc.paused": "一時停止",
    "link.netdata": "Netdata で詳細を見る",
    "sec.node": "ノード",
    "gauge.cpu": "CPU 使用率",
    "gauge.memory": "メモリ使用率",
    "gauge.disk": "ディスク使用率",
    "gauge.value": "{ratio}% ({used} / {total})",
    "note.metrics_missing": "メトリクスを取得できません",
    "note.disk_alert": "ディスク使用率が 85% を超えています (Discord 通知の対象)",
    "col.k3s_running": "稼働中の K3s",
    "col.k3s_latest": "最新の K3s (stable)",
    "note.k3s_update": "新しいバージョンがあります",
    "note.k3s_mixed": "ノード間で K3s のバージョンが異なります",
    "col.patches": "未適用の更新",
    "col.security": "修正済みの脆弱性に対応する更新",
    "col.reboot": "再起動",
    "reboot.required": "再起動が必要",
    "reboot.not_required": "不要",
    "sec.cluster": "クラスタ",
    "sub.argocd": "ArgoCD アプリケーション",
    "col.app": "アプリケーション",
    "col.sync": "同期状態",
    "col.health": "ヘルス",
    "sync.synced": "同期済み",
    "sync.outofsync": "差分あり",
    "sync.unknown": "不明",
    "health.healthy": "正常",
    "health.progressing": "更新中",
    "health.degraded": "劣化",
    "health.suspended": "一時停止",
    "health.missing": "リソースなし",
    "health.unknown": "不明",
    "sub.pods": "要注意の Pod",
    "col.pod": "Pod",
    "col.restarts": "再起動回数",
    "col.reason": "理由",
    "reason.crashloop": "再起動を繰り返しています (CrashLoopBackOff)",
    "reason.oom": "メモリ上限で強制終了されました (OOMKilled)",
    "sub.certs": "証明書",
    "col.cert": "証明書",
    "col.expires": "有効期限",
    "col.days_left": "残り日数",
    "note.cert_days": "有効期限まで {n} 日",
    "sub.eso": "シークレット同期",
    "col.secret": "ExternalSecret",
    "col.ready": "準備状態",
    "col.synced_at": "最終同期",
    "ready.true": "同期済み",
    "ready.false": "同期できていません",
    "sub.store": "ClusterSecretStore",
    "sec.data": "データ保護",
    "sub.cnpg": "データベース (CNPG)",
    "col.db": "クラスタ",
    "col.db_health": "ヘルス",
    "col.wal": "WAL アーカイブ",
    "col.last_backup": "最終バックアップ成功",
    "wal.ok": "正常",
    "wal.failing": "失敗しています",
    "note.backup_old": "最終バックアップから {duration} 経過しています",
    "sub.volsync": "メールデータのバックアップ (VolSync)",
    "col.volsync_target": "対象",
    "col.last_sync": "最終同期",
    "col.result": "結果",
    "result.successful": "成功",
    "result.failed": "失敗",
    "sec.connect": "外部接続・CI",
    "sub.tunnel": "Cloudflare Tunnel",
    "tunnel.healthy": "正常",
    "tunnel.degraded": "一部の接続が切断",
    "tunnel.down": "切断",
    "tunnel.inactive": "未接続",
    "tunnel.connections": "接続数: {n}",
    "sub.tailscale": "Tailscale",
    "col.device": "デバイス",
    "col.online": "オンライン",
    "col.last_seen": "最終接続",
    "online.true": "オンライン",
    "online.false": "オフライン",
    "sub.gha": "直近 7 日間に失敗したワークフロー",
    "col.workflow": "ワークフロー",
    "col.repo": "リポジトリ",
    "col.failed_at": "失敗日時",
    "col.link": "実行結果を開く",
    "sub.renovate": "未対応の Renovate PR",
    "col.pr": "プルリクエスト",
    "col.opened": "作成日",
    "sub.incidents": "対応中のインシデント",
    "incident.dr": "DR 検知 (dr-incident)",
    "incident.infra": "インフラ警告 (infra-alert)",
    "incident.none": "対応中のインシデントはありません",
    "sec.mail": "メール配送",
    "sub.queue": "配送キュー",
    "queue.active": "配送中",
    "queue.deferred": "再送待ち",
    "queue.hold": "保留",
    "queue.incoming": "受付中",
    "queue.oldest": "最も古い再送待ち: {duration} 前",
    "chart.delivery.title": "配送遅延・配送失敗の件数",
    "chart.delivery.x": "日時",
    "chart.delivery.y": "件数 (件)",
    "legend.deferred": "配送遅延 (再送待ち)",
    "legend.bounced": "配送失敗 (返送)",
    "sub.delivery_top": "失敗の多い宛先ドメイン",
    "col.domain": "宛先ドメイン",
    "col.count": "通数",
    "sub.tlsrpt": "TLS 配送レポート (TLS-RPT)",
    "chart.tlsrpt.title": "TLS 配送結果の推移",
    "chart.tlsrpt.x": "日付",
    "chart.tlsrpt.y": "セッション数",
    "legend.tls_success": "成功",
    "legend.tls_failure": "失敗",
    "col.reporter": "報告元",
    "sec.auth": "認証イベント (Zitadel)",
    "chart.auth.title": "認証失敗の推移",
    "chart.auth.x": "日時",
    "chart.auth.y": "件数 (件)",
    "legend.password": "パスワード誤り",
    "legend.otp": "ワンタイムパスワード誤り",
    "legend.otp_sms": "SMS コード誤り",
    "legend.otp_email": "メールコード誤り",
    "legend.passkey": "パスキー認証失敗",
    "legend.locked": "アカウントのロック",
    "sub.auth_recent": "直近の認証失敗",
    "col.time": "発生時刻",
    "col.event": "種別",
    "col.user": "ログイン名",
    "sec.falco": "侵入検知 (Falco)",
    "chart.falco_priority.title": "検知件数の推移 (優先度別)",
    "chart.falco_priority.x": "日時",
    "chart.falco_priority.y": "検知件数 (件)",
    "legend.emergency": "緊急 (Emergency)",
    "legend.alert": "警報 (Alert)",
    "legend.critical": "重大 (Critical)",
    "legend.error": "エラー (Error)",
    "legend.warning": "警告 (Warning)",
    "legend.notice": "通知 (Notice)",
    "legend.informational": "情報 (Informational)",
    "legend.debug": "デバッグ (Debug)",
    "chart.falco_rule.title": "ルール別の検知件数 (上位 10 件)",
    "chart.falco_rule.x": "検知件数 (件)",
    "chart.falco_rule.y": "ルール",
    "sub.falco_recent": "直近の検知",
    "col.rule": "ルール",
    "col.priority": "優先度",
    "col.target": "対象 (Namespace/Pod/コンテナ)",
    "col.summary": "概要",
    "empty.falco": "この期間の検知はありません",
    "note.falco_retention": "検知は 90 日間保存します",
    "note.falco_ingest_failed": "検知イベントの保存に失敗しています ({n} 件)。Discord への通知は継続しています",
    "sec.fail2ban": "fail2ban (メールサーバー)",
    "col.jail": "jail",
    "col.banned_count": "BAN 中の件数",
    "col.ip": "IP アドレス",
    "col.banned_at": "BAN 開始",
    "col.ban_until": "BAN 解除予定",
    "ban.permanent": "無期限",
    "empty.fail2ban": "現在 BAN されている IP はありません",
    "sec.dmarc": "DMARC 集計レポート",
    "chart.dmarc.title": "DMARC 評価結果の推移",
    "chart.dmarc.x": "日付",
    "chart.dmarc.y": "メール通数 (通)",
    "legend.dmarc_pass": "DMARC 合格",
    "legend.dmarc_fail": "DMARC 不合格",
    "sub.dmarc_sources": "送信元別の結果",
    "col.source_ip": "送信元 IP",
    "col.spf": "SPF",
    "col.dkim": "DKIM",
    "col.disposition": "受信側の処理",
    "eval.pass": "合格",
    "eval.fail": "不合格",
    "disposition.none": "配送",
    "disposition.quarantine": "隔離",
    "disposition.reject": "拒否",
    "note.ingest_failed": "解析できなかったレポートが {n} 件あります (直近 30 日)",
    "period.range": "{from} 〜 {until}",
    "period.open": "{from} 〜 (終了日なし)",
    "nav.billing": "課金・利用枠",
    "nav.monitoring": "既存監視",
    "nav.node": "ノード",
    "nav.cluster": "クラスタ",
    "nav.data": "データ保護",
    "nav.connect": "外部接続・CI",
    "nav.mail": "メール",
    "nav.auth": "認証イベント",
    "nav.falco": "Falco",
    "nav.fail2ban": "fail2ban",
    "nav.dmarc": "DMARC",
}


def label(key: str, **kw) -> str:
    """未定義キーは KeyError (typo を黙って通さない)。"""
    s = LABELS[key]
    return s.format(**kw) if kw else s
