---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailserver-dkim
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mailserver-dkim
    creationPolicy: Owner
  data:
    - secretKey: dkim-key
      remoteRef:
        key: MAILSERVER_DKIM_PRIVATE_KEY
