---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailserver-secrets
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mailserver-secrets
    creationPolicy: Owner
  data:
    # LDAP bind用トークン
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: MAILSERVER_LDAP_BIND_PASSWORD
    # Roundcube OAuth2 クライアントシークレット (OAUTHBEARER トークン検証用)
    - secretKey: MAIL_OAUTH2_CLIENT_SECRET
      remoteRef:
        key: ROUNDCUBE_OAUTH2_CLIENT_SECRET
