---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailserver-backup-healthcheck
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mailserver-backup-healthcheck
    creationPolicy: Owner
  data:
    - secretKey: HEALTHCHECKS_MAILSERVER_BACKUP_PING_URL
      remoteRef:
        key: HEALTHCHECKS_MAILSERVER_BACKUP_PING_URL
