---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mailserver-restic-secret
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mailserver-restic-secret
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: MAILSERVER_RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: MAILSERVER_RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: HETZNER_OS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: HETZNER_OS_SECRET_ACCESS_KEY
