---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: autoconfig
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:aramakisai/aramakisai-infra.git
    targetRevision: main
    path: gitops/manifests/prod/autoconfig
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
