---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.aramakisai.com
  oidc.config: |
    name: Authentik
    issuer: https://idp.aramakisai.com/application/o/argocd/
    clientID: argocd
    clientSecret: $argocd-oidc-secret:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  admin.enabled: "false"
