---
# Wiki.js アップロードファイル用ストレージ (/wiki/data/uploads マウント, requarks/wiki:2 イメージ)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-uploads
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
