---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snappymail-data
  namespace: prod
  labels:
    app: snappymail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
