---
apiVersion: v1
kind: Service
metadata:
  name: snappymail
  namespace: prod
  labels:
    app: snappymail
spec:
  type: ClusterIP
  selector:
    app: snappymail
  ports:
    - name: http
      port: 8888
      targetPort: 8888
